### ISSUE TITLE
Gnome 49 issue

### ISSUE THREAD

**Issue by stouracp** [maniacx/Bluetooth-Battery-Meter#84]
Fedora 43, Gnome 49.

While using this extension on Gnome 49, it is causing issue, when if this extension enabled, unable to connect/disconnect paired BT device from a top right corner menu.

**Comment by maniacx** [comment]
Can you send me a screenshot?
I am away from my linux workstation for few days. So I cannot test.

If you post screenshot a screen shot, I will get a better idea.

Also could you please try testing with popupsubmenu enabled and disabled

And reply in which mode, cam bluetooth device be disconnected/connected

![Image](https://github.com/user-attachments/assets/f2679e7b-6140-45ae-ba92-9a2dd5cd1651)

**Comment by stouracp** [comment]
It is happening if this menuitem is enabled. While disabled it works.

**Comment by maniacx** [comment]
When submenu is disabled, you can disconnect/ connect by checking on the menu.

When submenu is enabled, you can only connect and disconnect using button, (Bluetooth icon) . Clicking on menu itself does nothing.

Have a look at the picture in issue.

https://github.com/maniacx/Bluetooth-Battery-Meter/issues/78

This was done intentionally, just to avoid accidently disconnecting bluetooth device, while trying to expand submenu.

Are you clicking on the red part or yellow to connect/disconnect?

![Screenshot_20250923_010228_Chrome.jpg](https://github.com/user-attachments/assets/4e7452cf-e7ef-43b7-84f0-54b6f4d9451a)

**Comment by stouracp** [comment]
Aaah. But previously, it worked by clicking only on the menuitem itself, so there must be something changed recently.

**Comment by maniacx** [comment]
Previously, there was no submenu,

The purpose of the menu was to display icon with name, battery level and connect / disconnect using the menu itself.

With addition of submenu, I had to add an additional button to expand the submenu. So I decided to add another button  for  connecting /disconnecting device. 

Submenu are helpful for Airpods, as they offer additional buttons , slides for Noise cancelation and other features.

They are not so helpful if you dont have airpods. You can just disable submenu, if you do not need it.

**Comment by stouracp** [comment]
The clarification is fine, and makes sense, it was just not notified anywhere, at least I havent faound anything, so it was a confusing to me.

**Comment by maniacx** [comment]
Yeah apologize for that. I released it in a hurry. I am moving  so, had to pack the linux machine. Did not have time to update readme docs.

**Comment by stouracp** [comment]
No problem, I am also a bit of step ahead, running Fedora 43 beta, that is also a reason why I opened this, as I am trying to test it before a production. Thank you a lot.

**Comment by ponte-vecchio** [comment]
Seems to be working as intended at this stage.

Tested on Arch Linux with GNOME 49, Airpods Max.

**Comment by maniacx** [comment]
@ponte-vecchio 
@stouracp 

Thank you

**Comment by jtl5770** [comment]
I don't understand why the functionality of connect/disconnect had to go in this case. The submenu is only activated by the arrow down button. And having a connect/disconnect button also makes sense. But why shouldn't we still have the ability to use the rest of the entry, too for connect/disconnect? In the name of discoverability, this would make sense. I was also not aware that i suddenly had to press a tiny little button for that.

**Comment by maniacx** [comment]
> I don't understand why the functionality of connect/disconnect had to go in this case. The submenu is only activated by the arrow down button. And having a connect/disconnect button also makes sense. But why shouldn't we still have the ability to use the rest of the entry, too for connect/disconnect? In the name of discoverability, this would make sense. I was also not aware that i suddenly had to press a tiny little button for that.

 During development, I tested the submenu functionality multiple times to fine-tune the dimensions, button layout, and animations.

While testing, I accidentally clicked outside a button and ended up disconnecting my AirPods. This happened four times and made it clear that a connect/disconnect button was necessary. The available area is quite small, making accidental clicks easy. While an unintended AirPods disconnect is only a minor annoyance, the same issue could be a serious inconvenience if a user accidentally disconnects a Bluetooth keyboard or mouse.

You can disable the popup submenu from the settings. I assume you may already have the panel or system tray indicator enabled, which provides the same widget there as well:

https://maniacx.github.io/Bluetooth-Battery-Meter/preferences/quick-menu#enable-popup-submenu-widget-mode

Going forward, I plan to disable the Quick Settings submenu by default for new users and require them to explicitly enable it if needed. I also intend to provide an option to keep the original Quick Settings layout unchanged and rely solely on the indicator.

I understand that the button may be confusing for new users, but if the submenu option is enabled, I intend to keep it as a button.
